---
- hosts: all
  gather_facts: no
#  become: true
  vars_prompt:
    - name: "username"
      prompt: "what is the username?"
    - name: "password"
      prompt: "Enter password?"
  vars:
    ansible_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
  roles: 
   - pubkey
