#- name: Remove entry from local known_hosts
#  file:
#    dest: ~/.ssh/known_hosts
#    state: absent
#  delegate_to: localhost
#  run_once: true

- name: "Check hosts"
  setup:
  register: py_check
  failed_when: "py_check.module_stdout is defined and 'python' not in py_check.module_stdout"

- name: "install minimize"
  raw:  "sudo apt-get install nano dnsutils python-minimal rsync -y"
  when: "py_check.module_stdout is defined and 'python' in py_check.module_stdout"


- name: "Distribute pubkey authorization to nodes"
  remote_user: "{{ username }}"
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  with_items:
    - "{{ username }}"

- name: "Setup passwdless sudo"
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/etc/sudoers.d/{{ item }}"
    owner: root
    group: root
  with_items:
  - sudoers

- name: "Distribute pubkey authorization to nodes"
  remote_user: "{{ username }}"
  become: yes
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  with_items:
    - root

# Not available
#    key_options: 'no-port-forwarding,from="{{ subnets['15']['ips'][hostvars[inventory_hostname]['nodetype']] }}{{ hostvars[inventory_hostname]['nodeid'] }}"'
